spring:
  datasource:
    name: study_db
    url: jdbc:mysql://localhost:3306/study_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xbl237413
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 关闭模板引擎的缓存
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blog.bean

server:
  port: 8888


